# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).  

scrape_configs:

  - job_name: "soa-product-microservice"
    metrics_path: "/actuator/prometheus"

    static_configs:
      - targets: ["localhost:8081"]

  # Configuraci贸n para el servicio "soa-order-microservice"
  - job_name: "soa-order-microservice"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8082"]

  # Configuraci贸n para el servicio "soa-payment-microservice"
  - job_name: "soa-payment-microservice"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8083"]
  # Configuraci贸n para el servicio "soa-order-detail-microservice"
  - job_name: "soa-order-detail-microservice"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8084"]

  # Configuraci贸n para el servicio "soa-user-microservice"
  - job_name: "soa-user-microservice"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8085"]

  
