spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  application:
    name: soa-user-microservice

server:
  port: 8085


eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
    path: /soa-user-microservice/v3/api-docs
  swagger-ui:
    enabled: true
    path: /soa-user-microservice/swagger-ui.html

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
