spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  application:
    name: soa-gateway-microservice

server:
  port: 8099


eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
